language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    #- ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a
  global:   #Optional
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins
    - secure: "rRi5pYINR4B1lFZ6Pjm61YVp64CbXJRpbwd07ikpiWs/SAysoVNU7/86lrFpnhsucGXSJT4GuaYClsV1RbpxTcdvwRiBoU+niZhQdHyh4hj4ORizuEQac3kN4SJPC4OHJCec/XBSMdQuDr6Zsf1r+omNFYxwDkY
    E9nEeZTf6VFbn5WnmaPF6TzNU7PiWxjrJJSVbAprFDqvLVjATXpbUOiVvqrBBX/RtM+c7l22wmE1R9yreCCyq03xsESEvD4M9N5FIDJGXDpklX1rbHQ4F2FWuxo7pTgwMLMb3Ciu+geLlpmno1Dd3PZpW3yrWo8Qp9/wY6KoF1
    PPDI9WyeaW24iNsdiNAtGCPxKM9xxlFwEd2PnjvulctYbopgGwD3Y6ATqUu+zlEOHor+aNkLAlCMuqmYR0F8sEVWEXmuKvwVbdoi7ghkvLxdhf8BnSHNh/5h560KRAktPcAkVDDGH1Fmyc1kne0yylfYtD4diQQY5OalhzDKiJ
    U68BMTq+pp4pUXgVRmgalpBUI8rQkdNPzCuzOuAPkTNcFkxe+270VsnErlLFeHPlQNHchGtLXe9myR6RuGRP6v9zTqZgCZyKyNK2CzsjYKRfiswlYsnL5Ql3Fz9dGKdXm5R7EM9KXNZhjQft8wc4HiQMRxIouEwd4q8a3qJznW
    ht1dizz6OUWHkw="
    - secure: "K/LXtGGLFpNDxoiPTaw7oiaZPiM3ykcKkoACKrow+kuLW/XwXgi8zvXCWEm2rhN5mJdMOPA4FflxPHLO69ue+zw93ShgbIPJCFq8JA3aZZywk0Vz6luM0nsPfeNxCh03gYLuY07YbWi0OFt8Iq5rNmPiRsP61iX
    Zlf1Bcb8kKGAXvdTHAj88EIZycIMZremNTSRPm/YsRFya0fiDX/QtoybsUEH4PWXpQfDsNeI037uaSxW9JyQmOOlLVWJIjwlCc2CiKHbVtM9Fs4Pv/bHFZFdv+F9Pn2beDttWVX3a3sJHh5wuXLfNXTQo7VaECjxGdwqlhR243
    DIszuLArTUCMWyDstBjgTrWfFm9GyKEqSY/xBJ2i0nc6ZRPp+4LJgapFTMGpPh0p59J8JQ16VvlQAuqx78ETElhlTXDddNCbO71BuxlNHv4sWxVjqr09HPIbiwLTwOSjBtRXBWLD5oYNyZm0aSv9gjkvIbmGBGutxxG0DIpyKB
    iGbeAuZs9EMrABrCwZziiU0f2+90wrdRlYt/8228DvrAD6mamkmUhfynpfFTxnk/FBEkXYKGLczdtPAg3PdlfbkxpJyaVwOKoQSUy/JgOHw99mll0Mo7z+JVc2EE3WA2E0e4+m3u168C/x7gmf9+EYuXQ+bBKrQ+yLCSQKUmmH
    8GVwwGBCveJz7A="

android:
    update_sdk: true  #Check for the updates each time you run the build.
    components:
        - platform-tools
        - tools
        - build-tools-25.0.3    #Build tool version
        - android-25            #target api version
        - android-24
        - android-21

        # Additional components
        #- extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        #system images for emulator
        - sys-img-armeabi-v7a-android-21
        #- sys-img-armeabi-v7a-android-24

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

addons:
  sonarcloud:
    organization: "janaflauschata-github"
    token:
      secure: "CFS8P3YhB02c6YgUWZBJ+L49g5D+JtShGTJ4hiAaageY/TmZVdp1StntZ0UjDfQ0Gk3N748RfoKJmdi0cuYQQ72WxZJ2Jk/L3Ljn+e7F9AKkxwdBr+EKUW8x5dvSoG3LRrGL4KWD1djcuJyrLbta1xjOfTyVlzTBQeZr/4dWdehAaNXpfDObgTTG4vlrwsdueRVhbESvEGNRLjckiAP1Tak/zQUW5bvrVzAOi+vvbBVocapLoCYvG9FT+tqx+m5Ad72pGky5cVDDd8xZj7mrjdi35FWRawGBQsz7WjY6+/JnDY4P26RSzs3Slph58apsoBO0czgWedx+miRFKCOCJ1niiDXNBoZyQ6DwzrmZx0GrliH0B6Bcv4s9lEB7q36BT3rLwo2I4TxRFAyVQCXZAGLsRHAsXCWxeuusplHGHI8XPHHg2OY1HbuRRTj3k6U2ngF8qWId/CqHQnc0R4VGiofF4Nl0K+oFroG+G9SlsIxol8uRFgtZIF+EBCee/PAW9ebFw3WOxyikM/IRWpDGKQPPX4jdljJXUkUC8NQ3PeQ/LPdgoG6iZsD7ZlPnrssZay292dMRtbDw4TTrx/uNo7Zgk05iX9Wr+4bMt/J0IugDjTK/QkbbAFtzQOLRnyQIbGfH1pJ9sS52WufedfLKlj7qYhs4hSGaFFHs7c2i990="

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - pip install --user codecov    #Install codecov
  - openssl aes-256-cbc -K $encrypted_3bea847f446a_key -iv $encrypted_3bea847f446a_iv -in keystore.jks.enc -out keystore.jks -d

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle
    - $HOME/.sonar/cache

before_script:
    - chmod +x gradlew      #Grant permissions
    - android list targets
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
    - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
    - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
    - android-wait-for-emulator             #Run wait for the emulator script.
    - adb devices                           #Display list of devices
    - adb shell input keyevent 82 &
    - ./gradlew clean build jacocoTestReport connectedCheck sonarqube -PdisablePreDex --stacktrace

after_success:
- codecov

after_failure: cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml

before_deploy:
- cp $TRAVIS_BUILD_DIR/keystore.jks $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk releases
# Verification
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/25.0.3/zipalign -v 4 app-release-unsigned.apk traces.apk"

deploy:
  provider: releases
  api_key:
    secure: GjQlM3YKguTEt8Pw2Pi6l6f+WavL6Ygq1Od/c1hjndt9AzNUh0KDkC1+khWOVEd0a6oywyRBP0EvNa4oG8RH2Vh10tLAGAK7CMV+dPVU2JAjhpL873jkrnZnRS4wOU2in0zYzVoIdv7PujH2815pCFl3D3vRd2vfxf2XVK99bGgljhmAbNS/hsfpT/tPplRz0ZWRhVvhUS7p+uumeRQmRZY/jbjyWaX0e80HxtbkSRrcM06qiRViy4kK47C3vmGIKO5V6YDpGcJXdqz/DQzu3ywsdONU5K/S8uUovDt9/bVBoshCVesC/Fzv09bZqX8sZuZumo9yDxydQ1HaA7WncVLBUi2/IWa7IOuxaLoKfK/r1wKVPXwlWFYQE3Nj+BafDL8oax6HD9YtZT8FnlYGT6AxZKqbzK04qug1uPLXVyMoZj6LNGW52ALFgoAoNdiWAg36LWSEJmeD4QJlURsFJVDz7nGGXs3eLbFHM8ZelQIKA6F+6EcfO87aN4DYgj6g0D/lWLL/nMWDVrDWwEX9U6HS9wGtnKP7ibuxwppfflypu9NAIwoarYBO9TWjaAtFyH40wbB6SIzeUqlw9waM3uKExxacDWfJQs97wxTUH37VV1Nn+m+K+R4O9CFpLed9onJOjzTCQDRmHnIZzqXfbXMilade6L45tClYkv6WheY=
  file: traces.apk
  skip_cleanup: true
  on:
    repo: JanaFlauschata/traces
    tags: true