language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    #- ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a
  global:   #Optional
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

android:
    update_sdk: true  #Check for the updates each time you run the build.
    components:
        - platform-tools
        - tools
        - build-tools-25.0.3    #Build tool version
        - android-25            #target api version
        - android-24
        - android-21

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        #system images for emulator
        - sys-img-armeabi-v7a-android-21
        #- sys-img-armeabi-v7a-android-24

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

addons:
  sonarcloud:
    organization: "janaflauschata-github"
    token:
      secure: "CFS8P3YhB02c6YgUWZBJ+L49g5D+JtShGTJ4hiAaageY/TmZVdp1StntZ0UjDfQ0Gk3N748RfoKJmdi0cuYQQ72WxZJ2Jk/L3Ljn+e7F9AKkxwdBr+EKUW8x5dvSoG3LRrGL4KWD1djcuJyrLbta1xjOfTyVlzTBQeZr/4dWdehAaNXpfDObgTTG4vlrwsdueRVhbESvEGNRLjckiAP1Tak/zQUW5bvrVzAOi+vvbBVocapLoCYvG9FT+tqx+m5Ad72pGky5cVDDd8xZj7mrjdi35FWRawGBQsz7WjY6+/JnDY4P26RSzs3Slph58apsoBO0czgWedx+miRFKCOCJ1niiDXNBoZyQ6DwzrmZx0GrliH0B6Bcv4s9lEB7q36BT3rLwo2I4TxRFAyVQCXZAGLsRHAsXCWxeuusplHGHI8XPHHg2OY1HbuRRTj3k6U2ngF8qWId/CqHQnc0R4VGiofF4Nl0K+oFroG+G9SlsIxol8uRFgtZIF+EBCee/PAW9ebFw3WOxyikM/IRWpDGKQPPX4jdljJXUkUC8NQ3PeQ/LPdgoG6iZsD7ZlPnrssZay292dMRtbDw4TTrx/uNo7Zgk05iX9Wr+4bMt/J0IugDjTK/QkbbAFtzQOLRnyQIbGfH1pJ9sS52WufedfLKlj7qYhs4hSGaFFHs7c2i990="

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - pip install --user codecov    #Install codecov

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle
    - $HOME/.sonar/cache

before_script:
    - chmod +x gradlew      #Grant permissions
    - android list targets
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
    - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
    - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
    - android-wait-for-emulator             #Run wait for the emulator script.
    - adb devices                           #Display list of devices
    - adb shell input keyevent 82 &
    - ./gradlew jacocoTestReport connectedCheck connectedAndroidTest sonarqube -PdisablePreDex --stacktrace

after_success:
- codecov

after_failure: cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml

deploy:
  provider: releases
  api_key:
    secure: GjQlM3YKguTEt8Pw2Pi6l6f+WavL6Ygq1Od/c1hjndt9AzNUh0KDkC1+khWOVEd0a6oywyRBP0EvNa4oG8RH2Vh10tLAGAK7CMV+dPVU2JAjhpL873jkrnZnRS4wOU2in0zYzVoIdv7PujH2815pCFl3D3vRd2vfxf2XVK99bGgljhmAbNS/hsfpT/tPplRz0ZWRhVvhUS7p+uumeRQmRZY/jbjyWaX0e80HxtbkSRrcM06qiRViy4kK47C3vmGIKO5V6YDpGcJXdqz/DQzu3ywsdONU5K/S8uUovDt9/bVBoshCVesC/Fzv09bZqX8sZuZumo9yDxydQ1HaA7WncVLBUi2/IWa7IOuxaLoKfK/r1wKVPXwlWFYQE3Nj+BafDL8oax6HD9YtZT8FnlYGT6AxZKqbzK04qug1uPLXVyMoZj6LNGW52ALFgoAoNdiWAg36LWSEJmeD4QJlURsFJVDz7nGGXs3eLbFHM8ZelQIKA6F+6EcfO87aN4DYgj6g0D/lWLL/nMWDVrDWwEX9U6HS9wGtnKP7ibuxwppfflypu9NAIwoarYBO9TWjaAtFyH40wbB6SIzeUqlw9waM3uKExxacDWfJQs97wxTUH37VV1Nn+m+K+R4O9CFpLed9onJOjzTCQDRmHnIZzqXfbXMilade6L45tClYkv6WheY=
  file: traces.apk
  skip_cleanup: true
  on:
    repo: JanaFlauschata/traces
    tags: true

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"